### ISSUE TITLE
v0.5.4 fails to build with GCC 16 on Fedora 44

### ISSUE THREAD

**Issue by wmshi37** [block-hczhai/block2-preview#241]
v0.5.4 fails to compile on Fedora 44 with GCC 16, while v0.5.4rc16 builds successfully in the same environment.

My build command is:

```
cmake .. \
  -DUSE_MKL64=ON \
  -DBUILD_LIB=ON \
  -DLARGE_BOND=ON \
  -DMPI=ON

make clean
make -j
```

The same issue occurs with `USE_MKL64=OFF` on AMD CPUs with OpenBLAS, so it does not seem to be BLAS-related.

The error is:

```
/usr/include/c++/16/bits/stl_algobase.h:949:25: error:
‘__builtin_memset’ writing 1 or more bytes into a region of size 0
[-Werror=stringop-overflow=]

cc1plus: all warnings being treated as errors
```

It originates from `CompressedVector::clear() at fp_codec.hpp:441`, specifically `cache_dirty.resize(1)`.

The relevant change appears to be:

```
- mutable vector<bool> cache_dirty;
+ mutable vector<uint8_t> cache_dirty;
```

Adding

`-DCMAKE_CXX_FLAGS="-Wno-error=stringop-overflow"`

allows v0.5.4 to build successfully, with the same diagnostic remaining only as a warning.

While looking at this code, I also noticed a possible separate bounds issue in `finalize()`:

```
cache_dirty.resize(1);

...

for (int ic = 0; ic < ncache; ic++)
    if (cache_dirty[ic]) {
        ...
    }
```

Since `cache_dirty.size()` may be smaller than `ncache`, would it be safer for this loop to use `cache_dirty.size()` instead?
